### ISSUE TITLE
Having this error while activate plugin.

### ISSUE THREAD

**Issue by CryptoBeginner** [hashgraph/hedera-micropayment#2]
`Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/virtual/ascohosting.space/info/htdocs/wordpress/wp-content/plugins/hedera-micropayment-master/hedera-micropayment.php on line 23 Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/virtual/ascohosting.space/info/htdocs/wordpress/wp-content/plugins/hedera-micropayment-master/hedera-micropayment.php on line 23`

Hi im encounter this error while activating the plugin.

Is this plugin still ongoing?

**Comment by calvinchengx** [comment]
Run `compose install` to install the necessary dependencies.

**Comment by calvinchengx** [comment]
@CryptoBeginner see https://github.com/hashgraph/hedera-micropayment/blob/master/CONTRIBUTING.md

**Comment by CryptoBeginner** [comment]
Thanks calvinchengx

**Comment by calvinchengx** [comment]
no problem.
